[dependencies]
"php/php" = "=8.3.401"

[fs]
"/app/" = "app"
"/vendor/" = "vendor"

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]
